// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWF9SrrDdPv4zRzbWntvSWhBzIpJjvkqc',
    appId: '1:409331601156:web:67bbe747de0a16401e0a51',
    messagingSenderId: '409331601156',
    projectId: 'greenstem-86c8d',
    authDomain: 'greenstem-86c8d.firebaseapp.com',
    storageBucket: 'greenstem-86c8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1WOMbsMk3l9cocBV2NIF1tPIDNK59T9Q',
    appId: '1:409331601156:android:a6bd868bf29be5ea1e0a51',
    messagingSenderId: '409331601156',
    projectId: 'greenstem-86c8d',
    storageBucket: 'greenstem-86c8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNB2x-dIh3M8fedJYoL7EEDmOIX4lhh6M',
    appId: '1:409331601156:ios:407c0a365975b1cb1e0a51',
    messagingSenderId: '409331601156',
    projectId: 'greenstem-86c8d',
    storageBucket: 'greenstem-86c8d.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNB2x-dIh3M8fedJYoL7EEDmOIX4lhh6M',
    appId: '1:409331601156:ios:407c0a365975b1cb1e0a51',
    messagingSenderId: '409331601156',
    projectId: 'greenstem-86c8d',
    storageBucket: 'greenstem-86c8d.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWF9SrrDdPv4zRzbWntvSWhBzIpJjvkqc',
    appId: '1:409331601156:web:4118e9fe7d9548981e0a51',
    messagingSenderId: '409331601156',
    projectId: 'greenstem-86c8d',
    authDomain: 'greenstem-86c8d.firebaseapp.com',
    storageBucket: 'greenstem-86c8d.firebasestorage.app',
  );
}
